# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20160419_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('password', models.CharField(default='', editable=False, max_length=200)),
                ('first_name', models.CharField(default='', editable=False, max_length=200)),
                ('last_name', models.CharField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', editable=False, max_length=200)),
                ('time', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.Candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='test_case',
            name='cases',
        ),
        migrations.AddField(
            model_name='contest',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=' ', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='input_format',
            field=models.CharField(default=' ', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='output_format',
            field=models.CharField(default=' ', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='sample',
            field=models.TextField(default=' ', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test_case',
            name='inputs',
            field=models.CommaSeparatedIntegerField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='test_case',
            name='outputs',
            field=models.CommaSeparatedIntegerField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='test_case',
            name='sl_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_privilege',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='college_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(default=' ', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.Contest'),
        ),
    ]
