# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0010_auto_20160421_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=1, unique=True)),
                ('inputs', models.CommaSeparatedIntegerField(default='', max_length=200)),
                ('outputs', models.CommaSeparatedIntegerField(default='', max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.Question')),
            ],
        ),
    ]
