# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0014_auto_20160608_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_case',
            name='sl_no',
            field=models.IntegerField(default=1),
        ),
    ]
