# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0015_auto_20160609_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
