# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0016_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='no_of_test_cases',
        ),
    ]
