# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0018_auto_20160610_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(default='password', editable=False, max_length=200),
        ),
    ]
