# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0019_auto_20160610_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='user_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
