# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0020_auto_20160610_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.AddField(
            model_name='submission',
            name='question_no',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='sl_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_name',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
