# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0021_auto_20160617_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='no_of_questions',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='college_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='time',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sl_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
