# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0022_auto_20160620_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 6, 6, 7, 362965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 6, 6, 7, 362930, tzinfo=utc)),
        ),
    ]
