# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0023_auto_20160620_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='scores',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 11, 9, 26, 89860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 11, 9, 26, 89826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
