# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 05:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0024_auto_20160620_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 5, 43, 1, 62992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 5, 43, 1, 62957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
