# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0025_auto_20160621_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 6, 31, 28, 980044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 6, 31, 28, 980009, tzinfo=utc)),
        ),
    ]
