# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0026_auto_20160621_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='remtime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 7, 23, 59, 969566, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 7, 23, 59, 969530, tzinfo=utc)),
        ),
    ]
