# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0027_auto_20160621_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 8, 34, 45, 691083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 8, 34, 45, 691048, tzinfo=utc)),
        ),
    ]
