# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0028_auto_20160622_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 9, 10, 53, 81248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 9, 10, 53, 81214, tzinfo=utc)),
        ),
    ]
